src/RockPaperScissors/RpsWebsite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RpsWebsite.Entities;
using System;

namespace RpsWebsite.Controllers
{
    public class HomeController : Controller
    {
        private UserManager<User> _userManager;

        public HomeController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = _userManager.FindByNameAsync(User.Identity.Name).GetAwaiter().GetResult();
                if (user != null)
                {
                    ViewBag.PlayerWins = user.Wins;
                    ViewBag.PlayerLosses = user.Losses;
                    ViewBag.PlayerDraws = user.Draws;
                }
            }

            return View();
        }
    }
}

src/RockPaperScissors/RpsWebsite/Controllers/PlayController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RpsWebsite.Entities;
using RpsWebsite.Services;
using RpsWebsite.ViewModels;
using System;

namespace RpsWebsite.Controllers
{
    [Authorize]
    public class PlayController : Controller
    {
        private UserManager<User> _userManager;
        private IRpsServerClient _client;

        public PlayController(UserManager<User> userManager, IRpsServerClient client)
        {
            _userManager = userManager;
            _client = client;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var user = _userManager.FindByNameAsync(User.Identity.Name).GetAwaiter().GetResult();
            if (user == null || user.UserId == Guid.Empty)
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);

            ViewBag.PlayerId = user.UserId.ToString();
            ViewBag.PlayerWins = user.Wins;
            ViewBag.PlayerLosses = user.Losses;
            ViewBag.PlayerDraws = user.Draws;
            ViewBag.Endpoint = _client.Endpoint;

            return View();
        }

        [HttpPost("play/result/{security}")]
        public IActionResult Result(int security)
        {
            var user = _userManager.FindByNameAsync(User.Identity.Name).GetAwaiter().GetResult();
            if (user == null || user.UserId == Guid.Empty)
                return new BadRequestResult();

            // lolol I'll make this better if we keep working on this
            switch (security)
            {
                case 329847:
                    ++user.Wins;
                    break;

                case 87321:
                    ++user.Losses;
                    break;

                case 6719422:
                    ++user.Draws;
                    break;

                default:
                    return new StatusCodeResult(StatusCodes.Status402PaymentRequired); // pay me money and I'll let you cheat
            }

            _userManager.UpdateAsync(user).GetAwaiter().GetResult();

            return new OkResult();
        }
    }
}

src/RockPaperScissors/RpsWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Rock/Paper/Scissors";
}
<div class="text-center">
    <div class="jumbotron">
        <h2>Let's play Rock Paper Scissors with strangers!</h2>
        @if (User.Identity.IsAuthenticated)
        {
            <h2>[Your Record] Wins: @ViewBag.PlayerWins Draws: @ViewBag.PlayerDraws Losses: @ViewBag.PlayerLosses</h2>
        }
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div class="btn-group-vertical">
            <a class="btn btn-default btn-lg" asp-controller="Play" asp-action="Index">Play!</a>
        </div>
    }
    else
    {
        <div class="btn-group-vertical">
            <a class="btn btn-default btn-lg" asp-controller="Account" asp-action="Login">Log In</a>
            <a class="btn btn-default btn-lg" asp-controller="Account" asp-action="Register">Register</a>
        </div>
    }
</div>